# Generated by Django 4.1.7 on 2023-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='zoom_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='zoom_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
