# Generated by Django 4.1.7 on 2023-07-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0002_tutor_zoom_access_token_tutor_zoom_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='zoom_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
