# Generated by Django 4.1.7 on 2023-07-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
