# Generated by Django 4.1.7 on 2023-07-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0003_lessonplan_tutortask_scenario_question_grouptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_for_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutortask',
            name='lesson_plan',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='scenario',
            name='questions',
            field=models.ManyToManyField(related_name='scenarios', to='live_class.question'),
        ),
        migrations.DeleteModel(
            name='GroupTask',
        ),
        migrations.DeleteModel(
            name='TutorTask',
        ),
        migrations.AddField(
            model_name='task',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='live_class.lessonplan'),
        ),
    ]
