# Generated by Django 4.1.7 on 2023-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0003_tutor_zoom_token_expiration'),
        ('live_class', '0004_task_remove_tutortask_lesson_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='tutors',
            field=models.ManyToManyField(related_name='tutors', to='Tutors.tutor'),
        ),
    ]
