# Generated by Django 4.1.7 on 2023-08-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0006_timer_remove_scenario_questions_question_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='lesson_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_class.lessonplan'),
        ),
    ]
