# Generated by Django 4.1.7 on 2023-08-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0008_liveclass_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to='live_class.question'),
        ),
    ]
