# Generated by Django 4.1.7 on 2023-08-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0010_liveclass_currently_presenting'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='LiveClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_class', to='live_class.liveclass'),
        ),
    ]
