# Generated by Django 4.1.7 on 2023-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0012_lessonplan_lesson_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
