# Generated by Django 4.1.7 on 2023-09-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0014_interviewvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewvideo',
            name='embed_link',
            field=models.CharField(max_length=400),
        ),
    ]
