# Generated by Django 4.1.7 on 2023-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstudent',
            name='zoom_access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewstudent',
            name='zoom_refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
