# Generated by Django 4.1.7 on 2023-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstudent',
            name='enrolment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
