# Generated by Django 4.1.7 on 2023-07-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewstudent_enrolment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstudent',
            name='InterviewClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.interviewclass'),
        ),
    ]
