# Generated by Django 4.1.7 on 2023-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_rename_interview_student_interviewstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstudent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
