# Generated by Django 4.1.7 on 2023-07-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewstudent_interviewclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstudent',
            name='zoom_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
