# Generated by Django 4.1.7 on 2023-07-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0003_tutor_zoom_token_expiration'),
        ('interview', '0004_interviewstudent_zoom_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewstudent',
            name='InterviewClass',
        ),
        migrations.AddField(
            model_name='interviewclass',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tutors.tutor'),
        ),
        migrations.AddField(
            model_name='interviewstudent',
            name='interview_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='interview.interviewclass'),
        ),
    ]
