# Generated by Django 4.1.7 on 2023-03-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_reply_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
