# Generated by Django 4.1.7 on 2023-03-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_alter_comment_datetime_alter_reply_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='forum',
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.comment'),
        ),
    ]
