# Generated by Django 4.1.7 on 2023-02-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_ucatstudent_enrolment_date_ucatvideo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatsectioninstance',
            name='skills_mastered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
