# Generated by Django 4.1.7 on 2023-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_ucatsection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatvideo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
