# Generated by Django 4.1.7 on 2023-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_ucatvideo_testing_ucatvideo_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucatvideo',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
