# Generated by Django 4.1.7 on 2023-03-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0001_initial'),
        ('general', '0012_enrollment_ucatclass_enrollment_ucatclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatclass',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutors.tutor'),
        ),
    ]
