# Generated by Django 4.1.7 on 2023-03-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_ucatclass_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucatvideo',
            name='thumbnail',
        ),
    ]
