# Generated by Django 4.1.7 on 2023-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_remove_ucatvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatclass',
            name='class_notes',
            field=models.TextField(default='Class notes go here - Testing'),
            preserve_default=False,
        ),
    ]
