# Generated by Django 4.1.7 on 2023-03-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0001_initial'),
        ('general', '0015_ucatclass_class_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucatclass',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Tutors.tutor'),
        ),
        migrations.AlterField(
            model_name='ucatvideo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UcatProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UcatProblems', to='general.ucatstudent')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UcatProblems', to='general.ucatvideo')),
            ],
        ),
    ]
