# Generated by Django 4.1.7 on 2023-03-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_alter_ucatclass_tutor_alter_ucatvideo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatproblem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
