# Generated by Django 4.1.7 on 2023-04-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_syllabuspoint_alter_ucatstudent_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatvideo',
            name='syllabus_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.syllabuspoint'),
        ),
    ]
