# Generated by Django 4.1.7 on 2023-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_ucatvideo_syllabus_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucatstudent',
            name='tasks',
        ),
        migrations.AddField(
            model_name='ucatstudent',
            name='tasks_json',
            field=models.JSONField(default=dict),
        ),
    ]
