# Generated by Django 4.1.7 on 2023-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_remove_ucatstudent_tasks_ucatstudent_tasks_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucatvideo',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
