# Generated by Django 4.2.6 on 2024-01-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_ucatvideo_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuspoint',
            name='tiled',
            field=models.BooleanField(default=False),
        ),
    ]
